[package]
name = "pac-man"
version = "0.1.0"
authors = ["PeronTheDuck <pedroignacioperezvargas@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.85.0"
piston2d-graphics = "0.28.0"
piston2d-opengl_graphics = "0.57.0"
find_folder = "0.3.0"
csv = "1.0.5"